<a href="https://colab.research.google.com/github/anaya012391/CAPM-Analysis-Excel/blob/main/CAPM_Data_Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the pandas library, which is used for data manipulation and analysis.
import pandas as pd
import numpy as np

# Download financial data
import yfinance as yf

In [ ]:
tickers =["PG", "AAPL", "JPM", "XOM", "JNJ", "KO", "^GSPC"]
data = yf.download (
    tickers,
    start="2021-08-01",
    end="2026-08-01",
    interval="1mo",
    auto_adjust=False
)

[*********************100%***********************]  7 of 7 completed

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 60 entries, 2021-08-01 to 2026-07-01
Data columns (total 42 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Adj Close, AAPL)   60 non-null     float64
 1   (Adj Close, JNJ)    60 non-null     float64
 2   (Adj Close, JPM)    60 non-null     float64
 3   (Adj Close, KO)     60 non-null     float64
 4   (Adj Close, PG)     60 non-null     float64
 5   (Adj Close, XOM)    60 non-null     float64
 6   (Adj Close, ^GSPC)  60 non-null     float64
 7   (Close, AAPL)       60 non-null     float64
 8   (Close, JNJ)        60 non-null     float64
 9   (Close, JPM)        60 non-null     float64
 10  (Close, KO)         60 non-null     float64
 11  (Close, PG)         60 non-null     float64
 12  (Close, XOM)        60 non-null     float64
 13  (Close, ^GSPC)      60 non-null     float64
 14  (High, AAPL)        60 non-null     float64
 15  (High, JNJ)         60 non-null     float64
 16  (High, JPM)         60 non-null     float64
 17  (High, KO)          60 non-null     float64
 18  (High, PG)          60 non-null     float64
 19  (High, XOM)         60 non-null     float64
 20  (High, ^GSPC)       60 non-null     float64
 21  (Low, AAPL)         60 non-null     float64
 22  (Low, JNJ)          60 non-null     float64
 23  (Low, JPM)          60 non-null     float64
 24  (Low, KO)           60 non-null     float64
 25  (Low, PG)           60 non-null     float64
 26  (Low, XOM)          60 non-null     float64
 27  (Low, ^GSPC)        60 non-null     float64
 28  (Open, AAPL)        60 non-null     float64
 29  (Open, JNJ)         60 non-null     float64
 30  (Open, JPM)         60 non-null     float64
 31  (Open, KO)          60 non-null     float64
 32  (Open, PG)          60 non-null     float64
 33  (Open, XOM)         60 non-null     float64
 34  (Open, ^GSPC)       60 non-null     float64
 35  (Volume, AAPL)      60 non-null     int64
 36  (Volume, JNJ)       60 non-null     int64
 37  (Volume, JPM)       60 non-null     int64
 38  (Volume, KO)        60 non-null     int64
 39  (Volume, PG)        60 non-null     int64
 40  (Volume, XOM)       60 non-null     int64
 41  (Volume, ^GSPC)     60 non-null     int64
dtypes: float64(35), int64(7)
memory usage: 20.2 KB

In [ ]:
data.describe()

Price    Adj Close                                                             \
Ticker        AAPL         JNJ         JPM         KO          PG         XOM
count    60.000000   60.000000   60.000000  60.000000   60.000000   60.000000
mean    198.568524  163.169894  194.633535  60.955036  143.835788  100.266835
std      47.806335   31.518373   75.362953   9.318903   12.916698   25.392921
min     127.651512  135.518723   94.846558  45.597359  113.686081   45.754665
25%     161.486408  145.774609  130.632847  54.759011  135.584328   91.734438
50%     188.936569  151.368111  170.993149  57.357244  144.035721  100.900795
75%     232.039143  160.080067  258.208458  68.282372  152.841328  110.042263
max     311.791107  256.350006  351.790009  87.589996  170.843185  167.432053

Price                     Close                          ...        Open  \
Ticker        ^GSPC        AAPL         JNJ         JPM  ...          PG
count     60.000000   60.000000   60.000000   60.000000  ...   60.000000
mean    5242.252315  200.663999  173.812000  203.756668  ...  153.469833
std     1123.568490   46.931440   27.903790   71.984759  ...   10.988017
min     3585.620117  129.929993  144.589996  104.500000  ...  127.250000
25%     4264.487305  165.064995  156.214996  141.340004  ...  144.645000
50%     4940.669922  191.099998  164.135002  180.209999  ...  152.875000
75%     6034.417358  233.750000  177.299995  265.312492  ...  161.622505
max     7580.060059  312.059998  256.350006  351.790009  ...  179.119995

Price                                  Volume                              \
Ticker         XOM        ^GSPC          AAPL           JNJ           JPM
count    60.000000    60.000000  6.000000e+01  6.000000e+01  6.000000e+01
mean    106.760500  5190.513973  1.353072e+09  1.762633e+08  2.218987e+08
std      23.023206  1084.191096  3.805088e+08  1.214991e+08  6.001896e+07
min      54.490002  3609.780029  8.622723e+08  1.146407e+08  1.488284e+08
25%      99.944998  4263.707520  1.092841e+09  1.463311e+08  1.774650e+08
50%     110.709999  4819.625000  1.255840e+09  1.603850e+08  2.073240e+08
75%     116.150000  5968.660034  1.575639e+09  1.764418e+08  2.436087e+08
max     165.770004  7582.290039  2.444767e+09  1.084863e+09  4.584744e+08

Price
Ticker            KO            PG           XOM         ^GSPC
count   6.000000e+01  6.000000e+01  6.000000e+01  6.000000e+01
mean    3.213936e+08  1.559609e+08  3.977457e+08  9.439898e+10
std     6.073935e+07  3.243869e+07  1.086676e+08  1.511133e+10
min     2.045771e+08  1.043744e+08  2.748518e+08  7.086126e+10
25%     2.822152e+08  1.338849e+08  3.221104e+08  8.174485e+10
50%     3.155446e+08  1.479768e+08  3.788968e+08  8.950361e+10
75%     3.624957e+08  1.696286e+08  4.253929e+08  1.062016e+11
max     4.598818e+08  2.525912e+08  8.535001e+08  1.296617e+11

[8 rows x 42 columns]

In [ ]:
adjusted_close = data["Adj Close"].copy()

adjusted_close = adjusted_close.reset_index()

In [ ]:
adjusted_close.head()

Ticker,Date,AAPL,JNJ,JPM,KO,PG,XOM,^GSPC
0,2021-08-01,148.090591,151.309784,141.140900,48.567837,125.225510,45.754665,4522.680176
1,2021-09-01,138.015015,141.145584,144.441101,45.597359,122.947731,49.363342,4307.540039
2,2021-10-01,146.110580,142.351654,150.815369,48.986523,126.532784,54.104973,4605.379883
3,2021-11-01,161.464172,137.170212,140.997147,45.933441,127.939766,50.894268,4567.000000
4,2021-12-01,173.449432,150.488739,140.571014,51.853554,144.752975,52.042450,4766.180176

In [ ]:
adjusted_close

Ticker,Date,AAPL,JNJ,JPM,KO,PG,XOM,^GSPC
0,2021-08-01,148.090591,151.309784,141.140900,48.567837,125.225510,45.754665,4522.680176
1,2021-09-01,138.015015,141.145584,144.441101,45.597359,122.947731,49.363342,4307.540039
2,2021-10-01,146.110580,142.351654,150.815369,48.986523,126.532784,54.104973,4605.379883
3,2021-11-01,161.464172,137.170212,140.997147,45.933441,127.939766,50.894268,4567.000000
4,2021-12-01,173.449432,150.488739,140.571014,51.853554,144.752975,52.042450,4766.180176
5,2022-01-01,170.724182,151.561920,132.706467,53.429920,142.749847,64.604416,4515.549805
6,2022-02-01,161.493820,145.700073,126.633743,54.507103,138.692871,67.436043,4373.939941
7,2022-03-01,170.775406,156.908417,121.739861,54.712551,135.943756,71.021988,4530.410156
8,2022-04-01,154.187866,159.768082,107.383942,57.015774,143.640182,73.309410,4131.930176
9,2022-05-01,145.785202,159.966080,118.962624,55.930344,132.304626,83.399330,4132.149902
10,2022-06-01,133.913956,158.166183,101.311211,55.916683,128.645370,74.399155,3785.379883
11,2022-07-01,159.174683,155.502029,104.703354,57.036621,125.086189,84.207253,4130.290039
12,2022-08-01,154.207138,144.724213,103.223915,54.850086,124.212746,83.850006,3955.000000
13,2022-09-01,135.551636,146.536209,94.846558,50.155632,113.686081,76.586929,3585.620117
14,2022-10-01,150.401505,156.053467,115.273727,53.584694,122.128761,97.200745,3871.979980
15,2022-11-01,145.434113,160.699036,126.537361,57.354996,135.269409,98.451874,4080.110107
16,2022-12-01,127.651512,159.480225,122.801117,57.354996,137.445877,97.532280,3839.500000
17,2023-01-01,141.759705,147.536163,129.114090,55.290180,129.931030,102.581306,4076.600098
18,2023-02-01,145.046097,139.358841,132.241409,53.658161,125.532463,97.935249,3970.149902
19,2023-03-01,162.255615,140.941040,120.211914,56.359371,135.689301,97.712486,4109.310059
20,2023-04-01,166.959000,148.851913,128.528214,58.285572,143.600403,105.446800,4169.479980
21,2023-05-01,174.648834,142.059418,126.175972,54.206024,130.854691,91.837502,4179.830078
22,2023-06-01,191.123444,151.642395,135.222412,55.131546,139.339584,96.394310,4450.379883
23,2023-07-01,193.567032,153.483887,147.871460,56.697052,144.431259,96.385345,4588.959961
24,2023-08-01,185.362961,149.199814,136.984238,54.774498,142.620102,100.754738,4507.660156
25,2023-09-01,168.925262,143.727554,135.757904,51.656425,134.784027,106.545029,4288.049805
26,2023-10-01,168.491150,136.889542,131.139099,52.127026,139.512390,95.915894,4193.799805
27,2023-11-01,187.662125,143.864624,147.189621,54.355816,142.757736,93.949089,4567.799805
28,2023-12-01,190.211014,145.799454,160.411057,54.811573,136.267075,91.425247,4769.830078
29,2024-01-01,182.178909,147.808655,165.442337,55.332439,147.046799,94.013092,4845.649902
30,2024-02-01,178.800781,151.255356,176.543961,55.825397,148.731216,96.465034,5096.270020
31,2024-03-01,169.630753,148.265472,190.055664,57.359493,151.828583,107.281822,5254.350098
32,2024-04-01,168.493149,135.518723,182.994675,57.912643,153.703674,109.155373,5035.689941
33,2024-05-01,190.434692,138.579422,193.388000,59.000198,154.965698,109.102257,5277.509766
34,2024-06-01,208.631241,138.097580,193.034851,60.138283,155.323608,107.111153,5460.479980
35,2024-07-01,219.983032,149.142746,204.219498,63.057796,152.316269,110.339729,5522.299805
36,2024-08-01,227.100266,157.900330,215.735626,68.471672,162.530060,110.618423,5648.399902
37,2024-09-01,231.067093,154.282715,202.357727,68.360786,164.102875,109.943108,5762.479980
38,2024-10-01,224.035889,152.188278,214.276825,62.129730,157.424271,109.530411,5705.450195
39,2024-11-01,235.620117,148.755112,241.119400,61.421993,170.843185,111.546295,6032.379883
40,2024-12-01,248.615784,138.784348,231.454147,59.677475,159.778305,101.721207,5881.629883
41,2025-01-01,234.299683,146.010498,259.426910,60.846878,159.160904,101.021439,6040.529785
42,2025-02-01,240.361572,159.628830,256.854919,68.256233,166.687927,106.218437,5954.500000
43,2025-03-01,220.772064,160.422028,238.074890,69.155830,163.408615,113.469498,5611.850098
44,2025-04-01,211.200958,151.203369,238.877258,70.053841,156.853256,100.780151,5569.060059
45,2025-05-01,199.883957,151.426437,257.802307,69.619308,163.915848,98.501984,5911.689941
46,2025-06-01,204.183151,149.026428,283.104034,68.801491,153.717545,103.797798,6204.950195
47,2025-07-01,206.571625,160.724136,290.679108,66.020256,146.171570,107.495216,6339.390137
48,2025-08-01,231.285629,174.119858,295.761871,67.089951,152.553879,111.070869,6460.259766
49,2025-09-01,253.692886,182.227844,309.508850,64.988098,149.260712,109.574242,6688.459961
50,2025-10-01,269.374939,185.618439,306.763947,67.516296,147.095917,111.138893,6840.200195
51,2025-11-01,278.093048,204.648865,308.696503,71.651550,144.934036,113.640297,6849.089844
52,2025-12-01,271.122009,204.678528,317.708557,68.987183,140.189636,117.973381,6845.500000
53,2026-01-01,258.775665,224.755722,302.967682,73.822495,149.519547,138.619202,6939.029785
54,2026-02-01,263.709381,247.009430,297.431061,80.483398,164.720734,150.497406,6878.879883
55,2026-03-01,253.337891,243.042252,291.349731,75.562149,142.298233,167.432053,6528.520020
56,2026-04-01,270.866638,228.535690,311.825256,78.254768,146.000107,152.303360,7209.009766
57,2026-05-01,311.791107,225.330002,297.967682,78.503159,142.496262,144.325470,7580.060059
58,2026-06-01,289.110657,253.970001,325.862000,81.269997,145.553436,135.840408,7499.359863
59,2026-07-01,308.643829,256.350006,351.790009,87.589996,144.490005,154.439987,7489.720215